### ISSUE TITLE
Original Firmware

### ISSUE THREAD

**Issue by vik-patel** [ivanwick/bekantfirmware#13]
Hello,

I lost my backup of the original firmware ... can you please post or email it to me? ... want to keep a copy

Thanks

**Comment by ivanwick** [comment]
A dump of the OEM firmware has been posted at
https://github.com/ivanwick/bekantfirmware/issues/2#issuecomment-1013637468

Info about orginafirm.hex from the PICkit 2 Programmer software:

* Device: PIC16LF1938
* Configuration: 0FBC 1200
* User IDs: 80 84 80 85
* Checksum: A7D2

This matches the OEM firmware dump from my own unit marked "2015/34". Code protect was not enabled. Purchased in the US.
