### ISSUE TITLE
This is great.

### ISSUE THREAD

**Issue by iLLiac4** [ivanwick/bekantfirmware#2]
Great project. Have ordered a flasher to try it. I like the logic you have set.
A few more pictures of backing up and programming would be helpful for beginners. A link to programming program and recommended programmer.

**Comment by ivanwick** [comment]
Thanks for your interest.

In case you have not seen it yet, there is some more information about flashing the new firmware in my comment to issue #1. This will be incorporated it into new documentation.

What flashing device did you order? I used a PICKit 2 to dump and program mine, but it is an older device that is no longer supported by Microchip.

Also, what is the date code on your BEKANT control box? Look for a white sticker on the surface that touches the underside of the desk, formatted like "2015/34" (presumably for the 34th week of 2015).

**Comment by iLLiac4** [comment]
Hi. I have ordered this one https://de.aliexpress.com/item/1005002810022412.html PicKit2 with ICD2.
I have also find 'definition' file that contains more models. But will not know until i get the device https://github.com/GBert/misc/tree/master/pickit2/pk2dft
https://www.sfcompiler.co.uk/phpBB3/viewtopic.php?f=11&t=2076&p=11585#p11583

I have not yet opened the controllers since I will wait until I will not get the programmer but they were bought few years ago.

**Comment by ivanwick** [comment]
A [Firmware Programming Guide](https://github.com/ivanwick/bekantfirmware/blob/master/Documentation/programming-guide.md) is added to the documentation. I used a PICkit 2 and either the Windows GUI or pk2cmd CLI on Linux.

Please let me know if you are successful!

**Comment by iLLiac4** [comment]
TNX. Nicely written guide. Will report back ASAP i will get the PICkit2 if it works with this controller.

**Comment by ivanwick** [comment]
Hi @iLLiac4 Were you able to flash the firmware on your BEKANT microcontroller?

I have left this issue open as a place to assist with your installation but there have been no status updates.

Please let me know if you were successful or decided not to do it and I can close the issue.

**Comment by iLLiac4** [comment]
I am still waiting for a flashing controller. Delivery is disaster from China....

**Comment by iLLiac4** [comment]
I have got the controller and was able to flash it with your firmware. It did not autodetect it and was not able to make a working backup of the flash.
If possible I would ask for an original firmware dump so I can test it if it will work on my controller.


TNX

**Comment by WantedLange** [comment]
This is NOT verified or tested, but its the read from my original firmware
[orginafirm.hex.zip](https://github.com/ivanwick/bekantfirmware/files/7874509/orginafirm.hex.zip)

**Comment by iLLiac4** [comment]
Great TNX. It works.

**Comment by ivanwick** [comment]
Thanks for documenting your experience and tests.
