### ISSUE TITLE
PicKit 2 code protect

### ISSUE THREAD

**Issue by iLLiac4** [ivanwick/bekantfirmware#5]
Hi.

I have tried to flash the controller today and I was able to flash the pic but not to be able to read. 
I did try to do a backup of the original firmware but after checking it, it was zeros only.
Can someone please share an original backup of the firmware.
![image](https://user-images.githubusercontent.com/2831474/149612347-40e74dc2-47c4-48f2-88f9-a838d6c75b15.png)

**Comment by ceegames** [comment]
You have to 
1. read content
2. erase content
3. disable code protect under tools
4. write new content

The Bekant table needs to be unpowered for the code to work properly. Disconnect from power and press the Up/Down controls on the table to discharge any capacitors. Then write firmware while it's unpowered. Reconnect power and it should work. 

BACKUP FIRST!

**Comment by JulLeuverink** [comment]
Same here. When I try to read from the controller only zeros are diplayed. It seems like Ikea protects their code with the newer versions of the table. 

Can someone upload a backup of the original firmware?

**Comment by iLLiac4** [comment]
https://github.com/ivanwick/bekantfirmware/issues/2

**Comment by ivanwick** [comment]
Does your BEKANT control box have a date code? Mine is marked "2015/34" and code protect was not enabled. Purchased in the US.

A dump of the OEM firmware has been posted at
https://github.com/ivanwick/bekantfirmware/issues/2#issuecomment-1013637468

Info about orginafirm.hex from the PICkit 2 Programmer software:
* Device: PIC16LF1938
* Configuration: 0FBC 1200
* User IDs: 80 84 80 85
* Checksum: A7D2

This matches the OEM firmware dump from my own unit.

**Comment by JulLeuverink** [comment]
Yes it does. Purchased in Germany 2019 it has the date code "2019-32 Rec: C". But it has the same Controller and your firmware works absolutely flawless.
