### ISSUE TITLE
Installation Guide uncertainty

### ISSUE THREAD

**Issue by Cyklan** [ivanwick/bekantfirmware#7]
At the end of the installation guide it is stated to plug the controller back into the legs. However it never says to unplug the table in the first place.

Is unplugging the board from the table required or does it work with the board still plugged in?

**Comment by ivanwick** [comment]
You're right, the guide is not clear about unplugging the control box from the table, and the table from power. I do think it is best to power down the whole table, unplug the control box, reprogram it, plug in the reprogrammed control box, and restore power with it already connected.

Also note that the power brick I have does not drain power immediately after being unplugged, it maintains voltage for several seconds before the control board truly loses power. So power cycling should be done with that in mind.

Thank you for your interest. I will update the guide to be more explicit about unplugging and power cycling.

**Comment by ivanwick** [comment]
I added a couple sentences to the [Installation Guide](https://github.com/ivanwick/bekantfirmware/wiki/Installation-Guide) about disconnecting the desk from power, unplugging the control box from the desk, and doing the reverse after flashing firmware.
